controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

actuator:
    resource: '@SymSensorActuatorBundle/config/routing.yaml'
    prefix: /_actuator