name: Run Tests

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  phpstan:
    uses: ub-unibe-ch/github-workflows/.github/workflows/phpstan.yaml@v1
    with:
      php-version: "8.3"
    secrets:
      packagist-token: ${{ secrets.PACKAGIST_TOKEN }}

  php-cs-fixer:
    uses: ub-unibe-ch/github-workflows/.github/workflows/php-cs-fixer.yaml@v1
    with:
      php-version: "8.3"
    secrets:
      packagist-token: ${{ secrets.PACKAGIST_TOKEN }}

  phpunit:
    needs: [ "phpstan", "php-cs-fixer" ]
    uses: ub-unibe-ch/github-workflows/.github/workflows/phpunit.yaml@v1
    with:
      php-version: "8.3"
      build-assets: true
      database-init: 'migration'
    secrets:
      packagist-token: ${{ secrets.PACKAGIST_TOKEN }}
      node-token: ${{ secrets.NODE_AUTH_TOKEN }}
      ghcr-token: ${{ secrets.GITHUB_TOKEN }}

